basePath: /
host: localhost:8080
info:
  contact:
    name: Andrew Rutherfoord
  description: Implementation of a Billing Provider
  title: Billing Provider API
  version: "1.0"
paths:
  /cloud-service-providers:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              additionalProperties: true
              type: object
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List all cloud service providers supported by this billing provider
      tags:
      - cloud-service-providers
  /health:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health check
      tags:
      - health
swagger: "2.0"
