
# Billing Provider configuration

provider_id: "billing-provider-1"
provider_name: "Billing Provider 1"
mtls_key_path: "../keys/bp-1.key"
mtls_cert_path: "../keys/bp-1.crt"

cloud_service_providers:
  - id: "mock-csp-1"
    name: "MockCloud EU-West"
    api_endpoint: "https://csp-mock-adapter:8443"
    settlement_frequency: "weekly"
    mtls:
      common_name: "csp-adapter"
      cert_path: "../keys/csp-1.crt"
