
services:
  time-server:
    build:
      context: ./time-server
      dockerfile: Dockerfile
    container_name: mock-clock
    ports:
      - "9999:9999"
    volumes:
      - ./time-server/time-state.json:/root/time-state.json
    networks:
      - csp-network

  cloud-service-provider-customer-api:
    build:
      context: .
      dockerfile: csp-mock/Dockerfile.dev
      target: customer-api
    container_name: csp-mock-customer-api
    ports:
      - "8080:8080"
    volumes:
      - ./csp-mock:/app
      - ./keys:/keys
      - ./shared:/shared
      - csp-mock-tmp:/app/tmp
    environment:
      - CGO_ENABLED=1
      - MOCK_CLOCK_HOST=http://time-server:9999
    networks:
      - csp-network
    depends_on:
      - time-server

  cloud-service-provider-billing-provider-interface:
    build:
      context: .
      dockerfile: csp-mock/Dockerfile.dev
      target: billing-provider-interface
    ports:
      - "8443:8443"
    volumes:
      - ./csp-mock:/app
      - ./keys:/keys
      - ./shared:/shared
      - csp-mock-billing-tmp:/app/tmp
    environment:
      - CGO_ENABLED=1
      - MOCK_CLOCK_HOST=http://time-server:9999
    networks:
      - csp-network
    depends_on:
      - time-server

  billing-provider-csp-api:
    build:
      context: .
      dockerfile: billing-provider/Dockerfile.dev
      target: cloud-service-provider-api
    ports:
      - "8444:8444"
    volumes:
      - ./billing-provider:/app
      - ./keys:/keys
      - ./shared:/shared
      - billing-provider-csp-tmp:/app/tmp
    environment:
      - CGO_ENABLED=1
      - MOCK_CLOCK_HOST=http://time-server:9999
    networks:
      - csp-network
    depends_on:
      - time-server

  billing-provider-customer-api:
    build:
      context: .
      dockerfile: billing-provider/Dockerfile.dev
      target: customer-api
    ports:
      - "8081:8081"
    volumes:
      - ./billing-provider:/app
      - ./keys:/keys
      - ./shared:/shared
      - billing-provider-customer-tmp:/app/tmp
    environment:
      - CGO_ENABLED=1
      - MOCK_CLOCK_HOST=http://time-server:9999
    networks:
      - csp-network
    depends_on:
      - time-server

  customer-billing-api:
    build:
      context: .
      dockerfile: customer-billing/Dockerfile.dev
      target: customer-api
    ports:
      - "8082:8082"
    volumes:
      - ./customer-billing:/app
      - ./shared:/shared
      - customer-billing-tmp:/app/tmp
    environment:
      - API_PORT=8082
      - MOCK_CLOCK_HOST=http://time-server:9999
      - CB_DB_PATH=/app/customer-billing.sqlite
    networks:
      - csp-network
    depends_on:
      - time-server

networks:
  csp-network:
    driver: bridge

volumes:
  csp-mock-tmp:
  csp-mock-billing-tmp:
  billing-provider-csp-tmp:
  billing-provider-customer-tmp:
  customer-billing-tmp:
