// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing_account_cost_batch.sql

package db

import (
	"context"
	"time"
)

const createBillingAccountCostBatch = `-- name: CreateBillingAccountCostBatch :one
INSERT INTO billing_account_cost_batch (id, billing_account_id, billing_period_id, cloud_service_provider_id, total_items, total_cost, billed_currency, merkel_root, batch_signature, created_at, received_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, billing_account_id, billing_period_id, cloud_service_provider_id, total_items, total_cost, billed_currency, merkel_root, batch_signature, created_at, received_at
`

type CreateBillingAccountCostBatchParams struct {
	ID                     string
	BillingAccountID       string
	BillingPeriodID        string
	CloudServiceProviderID string
	TotalItems             int64
	TotalCost              float64
	BilledCurrency         string
	MerkelRoot             string
	BatchSignature         string
	CreatedAt              time.Time
	ReceivedAt             time.Time
}

func (q *Queries) CreateBillingAccountCostBatch(ctx context.Context, arg CreateBillingAccountCostBatchParams) (BillingAccountCostBatch, error) {
	row := q.db.QueryRowContext(ctx, createBillingAccountCostBatch,
		arg.ID,
		arg.BillingAccountID,
		arg.BillingPeriodID,
		arg.CloudServiceProviderID,
		arg.TotalItems,
		arg.TotalCost,
		arg.BilledCurrency,
		arg.MerkelRoot,
		arg.BatchSignature,
		arg.CreatedAt,
		arg.ReceivedAt,
	)
	var i BillingAccountCostBatch
	err := row.Scan(
		&i.ID,
		&i.BillingAccountID,
		&i.BillingPeriodID,
		&i.CloudServiceProviderID,
		&i.TotalItems,
		&i.TotalCost,
		&i.BilledCurrency,
		&i.MerkelRoot,
		&i.BatchSignature,
		&i.CreatedAt,
		&i.ReceivedAt,
	)
	return i, err
}

const getLatestBillingAccountCostBatchByAccount = `-- name: GetLatestBillingAccountCostBatchByAccount :one
SELECT id, billing_account_id, billing_period_id, cloud_service_provider_id, total_items, total_cost, billed_currency, merkel_root, batch_signature, created_at, received_at FROM billing_account_cost_batch
WHERE billing_account_id = ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestBillingAccountCostBatchByAccount(ctx context.Context, billingAccountID string) (BillingAccountCostBatch, error) {
	row := q.db.QueryRowContext(ctx, getLatestBillingAccountCostBatchByAccount, billingAccountID)
	var i BillingAccountCostBatch
	err := row.Scan(
		&i.ID,
		&i.BillingAccountID,
		&i.BillingPeriodID,
		&i.CloudServiceProviderID,
		&i.TotalItems,
		&i.TotalCost,
		&i.BilledCurrency,
		&i.MerkelRoot,
		&i.BatchSignature,
		&i.CreatedAt,
		&i.ReceivedAt,
	)
	return i, err
}

const listBillingAccountCostBatches = `-- name: ListBillingAccountCostBatches :many
SELECT id, billing_account_id, billing_period_id, cloud_service_provider_id, total_items, total_cost, billed_currency, merkel_root, batch_signature, created_at, received_at FROM billing_account_cost_batch
`

func (q *Queries) ListBillingAccountCostBatches(ctx context.Context) ([]BillingAccountCostBatch, error) {
	rows, err := q.db.QueryContext(ctx, listBillingAccountCostBatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillingAccountCostBatch
	for rows.Next() {
		var i BillingAccountCostBatch
		if err := rows.Scan(
			&i.ID,
			&i.BillingAccountID,
			&i.BillingPeriodID,
			&i.CloudServiceProviderID,
			&i.TotalItems,
			&i.TotalCost,
			&i.BilledCurrency,
			&i.MerkelRoot,
			&i.BatchSignature,
			&i.CreatedAt,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillingAccountCostBatchesByAccount = `-- name: ListBillingAccountCostBatchesByAccount :many
SELECT id, billing_account_id, billing_period_id, cloud_service_provider_id, total_items, total_cost, billed_currency, merkel_root, batch_signature, created_at, received_at FROM billing_account_cost_batch
WHERE billing_account_id = ?
`

func (q *Queries) ListBillingAccountCostBatchesByAccount(ctx context.Context, billingAccountID string) ([]BillingAccountCostBatch, error) {
	rows, err := q.db.QueryContext(ctx, listBillingAccountCostBatchesByAccount, billingAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillingAccountCostBatch
	for rows.Next() {
		var i BillingAccountCostBatch
		if err := rows.Scan(
			&i.ID,
			&i.BillingAccountID,
			&i.BillingPeriodID,
			&i.CloudServiceProviderID,
			&i.TotalItems,
			&i.TotalCost,
			&i.BilledCurrency,
			&i.MerkelRoot,
			&i.BatchSignature,
			&i.CreatedAt,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
