// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing_account_charge_batch.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createBillingAccountChargeBatch = `-- name: CreateBillingAccountChargeBatch :one
INSERT INTO billing_account_charge_batch (id, billing_account_id, billing_period_id, cloud_service_provider_id, total_items, total_cost, billed_currency, merkle_root, batch_signature, created_at, received_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, billing_account_id, billing_period_id, cloud_service_provider_id, total_items, total_cost, billed_currency, merkle_root, batch_signature, created_at, received_at
`

type CreateBillingAccountChargeBatchParams struct {
	ID                     string
	BillingAccountID       string
	BillingPeriodID        string
	CloudServiceProviderID string
	TotalItems             int64
	TotalCost              float64
	BilledCurrency         string
	MerkleRoot             string
	BatchSignature         string
	CreatedAt              time.Time
	ReceivedAt             time.Time
}

func (q *Queries) CreateBillingAccountChargeBatch(ctx context.Context, arg CreateBillingAccountChargeBatchParams) (BillingAccountChargeBatch, error) {
	row := q.db.QueryRowContext(ctx, createBillingAccountChargeBatch,
		arg.ID,
		arg.BillingAccountID,
		arg.BillingPeriodID,
		arg.CloudServiceProviderID,
		arg.TotalItems,
		arg.TotalCost,
		arg.BilledCurrency,
		arg.MerkleRoot,
		arg.BatchSignature,
		arg.CreatedAt,
		arg.ReceivedAt,
	)
	var i BillingAccountChargeBatch
	err := row.Scan(
		&i.ID,
		&i.BillingAccountID,
		&i.BillingPeriodID,
		&i.CloudServiceProviderID,
		&i.TotalItems,
		&i.TotalCost,
		&i.BilledCurrency,
		&i.MerkleRoot,
		&i.BatchSignature,
		&i.CreatedAt,
		&i.ReceivedAt,
	)
	return i, err
}

const getLatestBillingAccountChargeBatchByAccount = `-- name: GetLatestBillingAccountChargeBatchByAccount :one
SELECT id, billing_account_id, billing_period_id, cloud_service_provider_id, total_items, total_cost, billed_currency, merkle_root, batch_signature, created_at, received_at FROM billing_account_charge_batch
WHERE billing_account_id = ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestBillingAccountChargeBatchByAccount(ctx context.Context, billingAccountID string) (BillingAccountChargeBatch, error) {
	row := q.db.QueryRowContext(ctx, getLatestBillingAccountChargeBatchByAccount, billingAccountID)
	var i BillingAccountChargeBatch
	err := row.Scan(
		&i.ID,
		&i.BillingAccountID,
		&i.BillingPeriodID,
		&i.CloudServiceProviderID,
		&i.TotalItems,
		&i.TotalCost,
		&i.BilledCurrency,
		&i.MerkleRoot,
		&i.BatchSignature,
		&i.CreatedAt,
		&i.ReceivedAt,
	)
	return i, err
}

const listBillingAccountChargeBatches = `-- name: ListBillingAccountChargeBatches :many
SELECT id, billing_account_id, billing_period_id, cloud_service_provider_id, total_items, total_cost, billed_currency, merkle_root, batch_signature, created_at, received_at FROM billing_account_charge_batch
`

func (q *Queries) ListBillingAccountChargeBatches(ctx context.Context) ([]BillingAccountChargeBatch, error) {
	rows, err := q.db.QueryContext(ctx, listBillingAccountChargeBatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillingAccountChargeBatch
	for rows.Next() {
		var i BillingAccountChargeBatch
		if err := rows.Scan(
			&i.ID,
			&i.BillingAccountID,
			&i.BillingPeriodID,
			&i.CloudServiceProviderID,
			&i.TotalItems,
			&i.TotalCost,
			&i.BilledCurrency,
			&i.MerkleRoot,
			&i.BatchSignature,
			&i.CreatedAt,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillingAccountChargeBatchesByAccount = `-- name: ListBillingAccountChargeBatchesByAccount :many
SELECT id, billing_account_id, billing_period_id, cloud_service_provider_id, total_items, total_cost, billed_currency, merkle_root, batch_signature, created_at, received_at FROM billing_account_charge_batch
WHERE billing_account_id = ?
`

func (q *Queries) ListBillingAccountChargeBatchesByAccount(ctx context.Context, billingAccountID string) ([]BillingAccountChargeBatch, error) {
	rows, err := q.db.QueryContext(ctx, listBillingAccountChargeBatchesByAccount, billingAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillingAccountChargeBatch
	for rows.Next() {
		var i BillingAccountChargeBatch
		if err := rows.Scan(
			&i.ID,
			&i.BillingAccountID,
			&i.BillingPeriodID,
			&i.CloudServiceProviderID,
			&i.TotalItems,
			&i.TotalCost,
			&i.BilledCurrency,
			&i.MerkleRoot,
			&i.BatchSignature,
			&i.CreatedAt,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChargeBatchesOnlyReportedByCloudServiceProvider = `-- name: ListChargeBatchesOnlyReportedByCloudServiceProvider :many
SELECT csp.id, csp.billing_account_id, csp.cloud_service_provider_id, csp.total_items, csp.total_cost, csp.billed_currency, csp.merkle_root, csp.batch_signature, csp.created_at, csp.received_at FROM cloud_service_provider_charge_batch csp
WHERE csp.billing_account_id = ?
  AND NOT EXISTS (
    SELECT 1 FROM billing_account_charge_batch bp WHERE bp.id = csp.id
  )
ORDER BY csp.created_at DESC
`

// Charge batches the cloud service provider reported directly that the billing provider has
// not (yet) reported for this billing account.
func (q *Queries) ListChargeBatchesOnlyReportedByCloudServiceProvider(ctx context.Context, billingAccountID string) ([]CloudServiceProviderChargeBatch, error) {
	rows, err := q.db.QueryContext(ctx, listChargeBatchesOnlyReportedByCloudServiceProvider, billingAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CloudServiceProviderChargeBatch
	for rows.Next() {
		var i CloudServiceProviderChargeBatch
		if err := rows.Scan(
			&i.ID,
			&i.BillingAccountID,
			&i.CloudServiceProviderID,
			&i.TotalItems,
			&i.TotalCost,
			&i.BilledCurrency,
			&i.MerkleRoot,
			&i.BatchSignature,
			&i.CreatedAt,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChargeBatchesReportedByBillingProvider = `-- name: ListChargeBatchesReportedByBillingProvider :many
SELECT
    bp.id AS batch_id,
    bp.billing_account_id AS billing_account_id,
    bp.cloud_service_provider_id AS cloud_service_provider_id,
    bp.total_items AS bp_total_items,
    bp.total_cost AS bp_total_cost,
    bp.billed_currency AS bp_billed_currency,
    bp.merkle_root AS bp_merkle_root,
    bp.batch_signature AS bp_batch_signature,
    bp.created_at AS bp_created_at,
    bp.received_at AS bp_received_at,
    csp.total_items AS csp_total_items,
    csp.total_cost AS csp_total_cost,
    csp.billed_currency AS csp_billed_currency,
    csp.merkle_root AS csp_merkle_root,
    csp.batch_signature AS csp_batch_signature,
    csp.created_at AS csp_created_at,
    csp.received_at AS csp_received_at
FROM billing_account_charge_batch bp
LEFT JOIN cloud_service_provider_charge_batch csp ON csp.id = bp.id
WHERE bp.billing_account_id = ?
ORDER BY bp.created_at DESC
`

type ListChargeBatchesReportedByBillingProviderRow struct {
	BatchID                string
	BillingAccountID       string
	CloudServiceProviderID string
	BpTotalItems           int64
	BpTotalCost            float64
	BpBilledCurrency       string
	BpMerkleRoot           string
	BpBatchSignature       string
	BpCreatedAt            time.Time
	BpReceivedAt           time.Time
	CspTotalItems          sql.NullInt64
	CspTotalCost           sql.NullFloat64
	CspBilledCurrency      sql.NullString
	CspMerkleRoot          sql.NullString
	CspBatchSignature      sql.NullString
	CspCreatedAt           sql.NullTime
	CspReceivedAt          sql.NullTime
}

// Every charge batch the billing provider reported for this billing account, with the cloud
// service provider's own report of the same batch ID alongside it (nullable, since the CSP
// side may not have been fetched yet, or may simply disagree on whether the batch exists).
func (q *Queries) ListChargeBatchesReportedByBillingProvider(ctx context.Context, billingAccountID string) ([]ListChargeBatchesReportedByBillingProviderRow, error) {
	rows, err := q.db.QueryContext(ctx, listChargeBatchesReportedByBillingProvider, billingAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChargeBatchesReportedByBillingProviderRow
	for rows.Next() {
		var i ListChargeBatchesReportedByBillingProviderRow
		if err := rows.Scan(
			&i.BatchID,
			&i.BillingAccountID,
			&i.CloudServiceProviderID,
			&i.BpTotalItems,
			&i.BpTotalCost,
			&i.BpBilledCurrency,
			&i.BpMerkleRoot,
			&i.BpBatchSignature,
			&i.BpCreatedAt,
			&i.BpReceivedAt,
			&i.CspTotalItems,
			&i.CspTotalCost,
			&i.CspBilledCurrency,
			&i.CspMerkleRoot,
			&i.CspBatchSignature,
			&i.CspCreatedAt,
			&i.CspReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertInvoicedBillingAccountChargeBatch = `-- name: UpsertInvoicedBillingAccountChargeBatch :one
INSERT INTO billing_account_charge_batch (id, billing_account_id, billing_period_id, cloud_service_provider_id, total_items, total_cost, billed_currency, merkle_root, batch_signature, created_at, received_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET billing_period_id = excluded.billing_period_id
RETURNING id, billing_account_id, billing_period_id, cloud_service_provider_id, total_items, total_cost, billed_currency, merkle_root, batch_signature, created_at, received_at
`

type UpsertInvoicedBillingAccountChargeBatchParams struct {
	ID                     string
	BillingAccountID       string
	BillingPeriodID        string
	CloudServiceProviderID string
	TotalItems             int64
	TotalCost              float64
	BilledCurrency         string
	MerkleRoot             string
	BatchSignature         string
	CreatedAt              time.Time
	ReceivedAt             time.Time
}

// Used when syncing an invoice's batches: inserts the batch if the regular sync job hasn't
// seen it yet, or just marks it invoiced if it has.
func (q *Queries) UpsertInvoicedBillingAccountChargeBatch(ctx context.Context, arg UpsertInvoicedBillingAccountChargeBatchParams) (BillingAccountChargeBatch, error) {
	row := q.db.QueryRowContext(ctx, upsertInvoicedBillingAccountChargeBatch,
		arg.ID,
		arg.BillingAccountID,
		arg.BillingPeriodID,
		arg.CloudServiceProviderID,
		arg.TotalItems,
		arg.TotalCost,
		arg.BilledCurrency,
		arg.MerkleRoot,
		arg.BatchSignature,
		arg.CreatedAt,
		arg.ReceivedAt,
	)
	var i BillingAccountChargeBatch
	err := row.Scan(
		&i.ID,
		&i.BillingAccountID,
		&i.BillingPeriodID,
		&i.CloudServiceProviderID,
		&i.TotalItems,
		&i.TotalCost,
		&i.BilledCurrency,
		&i.MerkleRoot,
		&i.BatchSignature,
		&i.CreatedAt,
		&i.ReceivedAt,
	)
	return i, err
}
