// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing_providers.sql

package db

import (
	"context"
)

const createBillingProvider = `-- name: CreateBillingProvider :exec
INSERT INTO billing_providers (id, name, api_endpoint_url)
VALUES (?, ?, ?)
`

type CreateBillingProviderParams struct {
	ID             string
	Name           string
	ApiEndpointUrl string
}

func (q *Queries) CreateBillingProvider(ctx context.Context, arg CreateBillingProviderParams) error {
	_, err := q.db.ExecContext(ctx, createBillingProvider, arg.ID, arg.Name, arg.ApiEndpointUrl)
	return err
}

const getBillingProvider = `-- name: GetBillingProvider :one
SELECT id, name, api_endpoint_url FROM billing_providers
WHERE id = ?
`

func (q *Queries) GetBillingProvider(ctx context.Context, id string) (BillingProvider, error) {
	row := q.db.QueryRowContext(ctx, getBillingProvider, id)
	var i BillingProvider
	err := row.Scan(&i.ID, &i.Name, &i.ApiEndpointUrl)
	return i, err
}

const listBillingProviders = `-- name: ListBillingProviders :many
SELECT id, name, api_endpoint_url FROM billing_providers
`

func (q *Queries) ListBillingProviders(ctx context.Context) ([]BillingProvider, error) {
	rows, err := q.db.QueryContext(ctx, listBillingProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillingProvider
	for rows.Next() {
		var i BillingProvider
		if err := rows.Scan(&i.ID, &i.Name, &i.ApiEndpointUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBillingProvider = `-- name: UpsertBillingProvider :exec
INSERT INTO billing_providers (id, name, api_endpoint_url)
VALUES (?, ?, ?)
ON CONFLICT(id) DO UPDATE SET name = excluded.name, api_endpoint_url = excluded.api_endpoint_url
`

type UpsertBillingProviderParams struct {
	ID             string
	Name           string
	ApiEndpointUrl string
}

func (q *Queries) UpsertBillingProvider(ctx context.Context, arg UpsertBillingProviderParams) error {
	_, err := q.db.ExecContext(ctx, upsertBillingProvider, arg.ID, arg.Name, arg.ApiEndpointUrl)
	return err
}
