// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing_accounts.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createBillingAccount = `-- name: CreateBillingAccount :exec
INSERT INTO billing_accounts (id, billing_provider_id, alias, created_at)
VALUES (?, ?, ?, ?)
`

type CreateBillingAccountParams struct {
	ID                string
	BillingProviderID string
	Alias             string
	CreatedAt         time.Time
}

func (q *Queries) CreateBillingAccount(ctx context.Context, arg CreateBillingAccountParams) error {
	_, err := q.db.ExecContext(ctx, createBillingAccount,
		arg.ID,
		arg.BillingProviderID,
		arg.Alias,
		arg.CreatedAt,
	)
	return err
}

const getBillingAccount = `-- name: GetBillingAccount :one
SELECT id, billing_provider_id, alias, created_at, onboarding_redirect_url, onboarding_complete FROM billing_accounts
WHERE id = ?
`

func (q *Queries) GetBillingAccount(ctx context.Context, id string) (BillingAccount, error) {
	row := q.db.QueryRowContext(ctx, getBillingAccount, id)
	var i BillingAccount
	err := row.Scan(
		&i.ID,
		&i.BillingProviderID,
		&i.Alias,
		&i.CreatedAt,
		&i.OnboardingRedirectUrl,
		&i.OnboardingComplete,
	)
	return i, err
}

const listBillingAccounts = `-- name: ListBillingAccounts :many
SELECT ba.id, ba.billing_provider_id, ba.alias, ba.created_at, ba.onboarding_redirect_url, ba.onboarding_complete, bp.name AS billing_provider_name, bp.api_endpoint_url  AS billing_provider_base_url
FROM billing_accounts ba
LEFT JOIN billing_providers bp ON bp.id = ba.billing_provider_id
`

type ListBillingAccountsRow struct {
	ID                     string
	BillingProviderID      string
	Alias                  string
	CreatedAt              time.Time
	OnboardingRedirectUrl  sql.NullString
	OnboardingComplete     sql.NullTime
	BillingProviderName    sql.NullString
	BillingProviderBaseUrl sql.NullString
}

func (q *Queries) ListBillingAccounts(ctx context.Context) ([]ListBillingAccountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBillingAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBillingAccountsRow
	for rows.Next() {
		var i ListBillingAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.BillingProviderID,
			&i.Alias,
			&i.CreatedAt,
			&i.OnboardingRedirectUrl,
			&i.OnboardingComplete,
			&i.BillingProviderName,
			&i.BillingProviderBaseUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillingAccountsByProvider = `-- name: ListBillingAccountsByProvider :many
SELECT id, billing_provider_id, alias, created_at, onboarding_redirect_url, onboarding_complete FROM billing_accounts
WHERE billing_provider_id = ?
`

func (q *Queries) ListBillingAccountsByProvider(ctx context.Context, billingProviderID string) ([]BillingAccount, error) {
	rows, err := q.db.QueryContext(ctx, listBillingAccountsByProvider, billingProviderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillingAccount
	for rows.Next() {
		var i BillingAccount
		if err := rows.Scan(
			&i.ID,
			&i.BillingProviderID,
			&i.Alias,
			&i.CreatedAt,
			&i.OnboardingRedirectUrl,
			&i.OnboardingComplete,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBillingAccountOnboarding = `-- name: UpdateBillingAccountOnboarding :exec
UPDATE billing_accounts
SET onboarding_redirect_url = ?, onboarding_complete = ?
WHERE id = ?
`

type UpdateBillingAccountOnboardingParams struct {
	OnboardingRedirectUrl sql.NullString
	OnboardingComplete    sql.NullTime
	ID                    string
}

func (q *Queries) UpdateBillingAccountOnboarding(ctx context.Context, arg UpdateBillingAccountOnboardingParams) error {
	_, err := q.db.ExecContext(ctx, updateBillingAccountOnboarding, arg.OnboardingRedirectUrl, arg.OnboardingComplete, arg.ID)
	return err
}
