// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cloud_service_provider_charge_batch.sql

package db

import (
	"context"
	"time"
)

const createCloudServiceProviderChargeBatch = `-- name: CreateCloudServiceProviderChargeBatch :one
INSERT INTO cloud_service_provider_charge_batch (id, billing_account_id, cloud_service_provider_id, total_items, total_cost, billed_currency, merkle_root, batch_signature, created_at, received_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, billing_account_id, cloud_service_provider_id, total_items, total_cost, billed_currency, merkle_root, batch_signature, created_at, received_at
`

type CreateCloudServiceProviderChargeBatchParams struct {
	ID                     string
	BillingAccountID       string
	CloudServiceProviderID string
	TotalItems             int64
	TotalCost              float64
	BilledCurrency         string
	MerkleRoot             string
	BatchSignature         string
	CreatedAt              time.Time
	ReceivedAt             time.Time
}

func (q *Queries) CreateCloudServiceProviderChargeBatch(ctx context.Context, arg CreateCloudServiceProviderChargeBatchParams) (CloudServiceProviderChargeBatch, error) {
	row := q.db.QueryRowContext(ctx, createCloudServiceProviderChargeBatch,
		arg.ID,
		arg.BillingAccountID,
		arg.CloudServiceProviderID,
		arg.TotalItems,
		arg.TotalCost,
		arg.BilledCurrency,
		arg.MerkleRoot,
		arg.BatchSignature,
		arg.CreatedAt,
		arg.ReceivedAt,
	)
	var i CloudServiceProviderChargeBatch
	err := row.Scan(
		&i.ID,
		&i.BillingAccountID,
		&i.CloudServiceProviderID,
		&i.TotalItems,
		&i.TotalCost,
		&i.BilledCurrency,
		&i.MerkleRoot,
		&i.BatchSignature,
		&i.CreatedAt,
		&i.ReceivedAt,
	)
	return i, err
}

const getLatestCloudServiceProviderChargeBatchByAccount = `-- name: GetLatestCloudServiceProviderChargeBatchByAccount :one
SELECT id, billing_account_id, cloud_service_provider_id, total_items, total_cost, billed_currency, merkle_root, batch_signature, created_at, received_at FROM cloud_service_provider_charge_batch
WHERE billing_account_id = ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestCloudServiceProviderChargeBatchByAccount(ctx context.Context, billingAccountID string) (CloudServiceProviderChargeBatch, error) {
	row := q.db.QueryRowContext(ctx, getLatestCloudServiceProviderChargeBatchByAccount, billingAccountID)
	var i CloudServiceProviderChargeBatch
	err := row.Scan(
		&i.ID,
		&i.BillingAccountID,
		&i.CloudServiceProviderID,
		&i.TotalItems,
		&i.TotalCost,
		&i.BilledCurrency,
		&i.MerkleRoot,
		&i.BatchSignature,
		&i.CreatedAt,
		&i.ReceivedAt,
	)
	return i, err
}

const listCloudServiceProviderChargeBatchesByAccount = `-- name: ListCloudServiceProviderChargeBatchesByAccount :many
SELECT id, billing_account_id, cloud_service_provider_id, total_items, total_cost, billed_currency, merkle_root, batch_signature, created_at, received_at FROM cloud_service_provider_charge_batch
WHERE billing_account_id = ?
`

func (q *Queries) ListCloudServiceProviderChargeBatchesByAccount(ctx context.Context, billingAccountID string) ([]CloudServiceProviderChargeBatch, error) {
	rows, err := q.db.QueryContext(ctx, listCloudServiceProviderChargeBatchesByAccount, billingAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CloudServiceProviderChargeBatch
	for rows.Next() {
		var i CloudServiceProviderChargeBatch
		if err := rows.Scan(
			&i.ID,
			&i.BillingAccountID,
			&i.CloudServiceProviderID,
			&i.TotalItems,
			&i.TotalCost,
			&i.BilledCurrency,
			&i.MerkleRoot,
			&i.BatchSignature,
			&i.CreatedAt,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
