// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cloud_service_providers.sql

package db

import (
	"context"
)

const createCloudServiceProvider = `-- name: CreateCloudServiceProvider :exec
INSERT INTO cloud_service_providers (id, billing_provider_id, name, api_endpoint_url, customer_api_endpoint_url)
VALUES (?, ?, ?, ?, ?)
`

type CreateCloudServiceProviderParams struct {
	ID                     string
	BillingProviderID      string
	Name                   string
	ApiEndpointUrl         string
	CustomerApiEndpointUrl string
}

func (q *Queries) CreateCloudServiceProvider(ctx context.Context, arg CreateCloudServiceProviderParams) error {
	_, err := q.db.ExecContext(ctx, createCloudServiceProvider,
		arg.ID,
		arg.BillingProviderID,
		arg.Name,
		arg.ApiEndpointUrl,
		arg.CustomerApiEndpointUrl,
	)
	return err
}

const deleteCloudServiceProvidersByBillingProvider = `-- name: DeleteCloudServiceProvidersByBillingProvider :exec
DELETE FROM cloud_service_providers
WHERE billing_provider_id = ?
`

func (q *Queries) DeleteCloudServiceProvidersByBillingProvider(ctx context.Context, billingProviderID string) error {
	_, err := q.db.ExecContext(ctx, deleteCloudServiceProvidersByBillingProvider, billingProviderID)
	return err
}

const getCloudServiceProvider = `-- name: GetCloudServiceProvider :one
SELECT id, billing_provider_id, name, api_endpoint_url, customer_api_endpoint_url FROM cloud_service_providers
WHERE id = ?
`

func (q *Queries) GetCloudServiceProvider(ctx context.Context, id string) (CloudServiceProvider, error) {
	row := q.db.QueryRowContext(ctx, getCloudServiceProvider, id)
	var i CloudServiceProvider
	err := row.Scan(
		&i.ID,
		&i.BillingProviderID,
		&i.Name,
		&i.ApiEndpointUrl,
		&i.CustomerApiEndpointUrl,
	)
	return i, err
}

const listCloudServiceProvidersByBillingProvider = `-- name: ListCloudServiceProvidersByBillingProvider :many
SELECT id, billing_provider_id, name, api_endpoint_url, customer_api_endpoint_url FROM cloud_service_providers
WHERE billing_provider_id = ?
`

func (q *Queries) ListCloudServiceProvidersByBillingProvider(ctx context.Context, billingProviderID string) ([]CloudServiceProvider, error) {
	rows, err := q.db.QueryContext(ctx, listCloudServiceProvidersByBillingProvider, billingProviderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CloudServiceProvider
	for rows.Next() {
		var i CloudServiceProvider
		if err := rows.Scan(
			&i.ID,
			&i.BillingProviderID,
			&i.Name,
			&i.ApiEndpointUrl,
			&i.CustomerApiEndpointUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCloudServiceProviderCustomerEndpoint = `-- name: UpdateCloudServiceProviderCustomerEndpoint :one
UPDATE cloud_service_providers
SET name = ?, customer_api_endpoint_url = ?
WHERE id = ?
RETURNING id, billing_provider_id, name, api_endpoint_url, customer_api_endpoint_url
`

type UpdateCloudServiceProviderCustomerEndpointParams struct {
	Name                   string
	CustomerApiEndpointUrl string
	ID                     string
}

func (q *Queries) UpdateCloudServiceProviderCustomerEndpoint(ctx context.Context, arg UpdateCloudServiceProviderCustomerEndpointParams) (CloudServiceProvider, error) {
	row := q.db.QueryRowContext(ctx, updateCloudServiceProviderCustomerEndpoint, arg.Name, arg.CustomerApiEndpointUrl, arg.ID)
	var i CloudServiceProvider
	err := row.Scan(
		&i.ID,
		&i.BillingProviderID,
		&i.Name,
		&i.ApiEndpointUrl,
		&i.CustomerApiEndpointUrl,
	)
	return i, err
}
