// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cloud_service_provider_accounts.sql

package db

import (
	"context"
	"database/sql"
)

const createCloudServiceProviderAccount = `-- name: CreateCloudServiceProviderAccount :one
INSERT INTO cloud_service_provider_accounts (id, billing_account_id, cloud_service_provider_id)
VALUES (?, ?, ?)
RETURNING id, billing_account_id, cloud_service_provider_id
`

type CreateCloudServiceProviderAccountParams struct {
	ID                     string
	BillingAccountID       string
	CloudServiceProviderID string
}

func (q *Queries) CreateCloudServiceProviderAccount(ctx context.Context, arg CreateCloudServiceProviderAccountParams) (CloudServiceProviderAccount, error) {
	row := q.db.QueryRowContext(ctx, createCloudServiceProviderAccount, arg.ID, arg.BillingAccountID, arg.CloudServiceProviderID)
	var i CloudServiceProviderAccount
	err := row.Scan(&i.ID, &i.BillingAccountID, &i.CloudServiceProviderID)
	return i, err
}

const getCloudServiceProviderAccount = `-- name: GetCloudServiceProviderAccount :one
SELECT id, billing_account_id, cloud_service_provider_id FROM cloud_service_provider_accounts
WHERE id = ?
`

func (q *Queries) GetCloudServiceProviderAccount(ctx context.Context, id string) (CloudServiceProviderAccount, error) {
	row := q.db.QueryRowContext(ctx, getCloudServiceProviderAccount, id)
	var i CloudServiceProviderAccount
	err := row.Scan(&i.ID, &i.BillingAccountID, &i.CloudServiceProviderID)
	return i, err
}

const listCloudServiceProviderAccountsByBillingAccountWithTotalCost = `-- name: ListCloudServiceProviderAccountsByBillingAccountWithTotalCost :many
SELECT cspa.id, cspa.billing_account_id, cspa.cloud_service_provider_id, csp.name AS cloud_service_provider_name, csp.customer_api_endpoint_url AS customer_api_endpoint_url, SUM(bacb.total_cost) AS total_cost, bacb.billed_currency AS billing_currency
FROM cloud_service_provider_accounts cspa
JOIN cloud_service_providers csp ON csp.id = cspa.cloud_service_provider_id
LEFT JOIN billing_account_charge_batch bacb ON bacb.cloud_service_provider_id = cspa.cloud_service_provider_id AND bacb.billing_account_id = cspa.billing_account_id
WHERE cspa.billing_account_id = ?
GROUP BY cspa.id, cspa.billing_account_id, cspa.cloud_service_provider_id, csp.name, csp.customer_api_endpoint_url, bacb.billed_currency
`

type ListCloudServiceProviderAccountsByBillingAccountWithTotalCostRow struct {
	ID                       string
	BillingAccountID         string
	CloudServiceProviderID   string
	CloudServiceProviderName string
	CustomerApiEndpointUrl   string
	TotalCost                sql.NullFloat64
	BillingCurrency          sql.NullString
}

func (q *Queries) ListCloudServiceProviderAccountsByBillingAccountWithTotalCost(ctx context.Context, billingAccountID string) ([]ListCloudServiceProviderAccountsByBillingAccountWithTotalCostRow, error) {
	rows, err := q.db.QueryContext(ctx, listCloudServiceProviderAccountsByBillingAccountWithTotalCost, billingAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCloudServiceProviderAccountsByBillingAccountWithTotalCostRow
	for rows.Next() {
		var i ListCloudServiceProviderAccountsByBillingAccountWithTotalCostRow
		if err := rows.Scan(
			&i.ID,
			&i.BillingAccountID,
			&i.CloudServiceProviderID,
			&i.CloudServiceProviderName,
			&i.CustomerApiEndpointUrl,
			&i.TotalCost,
			&i.BillingCurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
