// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cloud_service_provider_accounts.sql

package db

import (
	"context"
)

const createCloudServiceProviderAccount = `-- name: CreateCloudServiceProviderAccount :one
INSERT INTO cloud_service_provider_accounts (id, billing_account_id, cloud_provider_id)
VALUES (?, ?, ?)
RETURNING id, billing_account_id, cloud_provider_id
`

type CreateCloudServiceProviderAccountParams struct {
	ID               string
	BillingAccountID string
	CloudProviderID  string
}

func (q *Queries) CreateCloudServiceProviderAccount(ctx context.Context, arg CreateCloudServiceProviderAccountParams) (CloudServiceProviderAccount, error) {
	row := q.db.QueryRowContext(ctx, createCloudServiceProviderAccount, arg.ID, arg.BillingAccountID, arg.CloudProviderID)
	var i CloudServiceProviderAccount
	err := row.Scan(&i.ID, &i.BillingAccountID, &i.CloudProviderID)
	return i, err
}

const getCloudServiceProviderAccount = `-- name: GetCloudServiceProviderAccount :one
SELECT id, billing_account_id, cloud_provider_id FROM cloud_service_provider_accounts
WHERE id = ?
`

func (q *Queries) GetCloudServiceProviderAccount(ctx context.Context, id string) (CloudServiceProviderAccount, error) {
	row := q.db.QueryRowContext(ctx, getCloudServiceProviderAccount, id)
	var i CloudServiceProviderAccount
	err := row.Scan(&i.ID, &i.BillingAccountID, &i.CloudProviderID)
	return i, err
}

const listCloudServiceProviderAccountsByBillingAccount = `-- name: ListCloudServiceProviderAccountsByBillingAccount :many
SELECT cspa.id, cspa.billing_account_id, cspa.cloud_provider_id, bpsc.name AS cloud_provider_name
FROM cloud_service_provider_accounts cspa
JOIN billing_provider_supported_cloud_provider bpsc ON bpsc.id = cspa.cloud_provider_id
WHERE cspa.billing_account_id = ?
`

type ListCloudServiceProviderAccountsByBillingAccountRow struct {
	ID                string
	BillingAccountID  string
	CloudProviderID   string
	CloudProviderName string
}

func (q *Queries) ListCloudServiceProviderAccountsByBillingAccount(ctx context.Context, billingAccountID string) ([]ListCloudServiceProviderAccountsByBillingAccountRow, error) {
	rows, err := q.db.QueryContext(ctx, listCloudServiceProviderAccountsByBillingAccount, billingAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCloudServiceProviderAccountsByBillingAccountRow
	for rows.Next() {
		var i ListCloudServiceProviderAccountsByBillingAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.BillingAccountID,
			&i.CloudProviderID,
			&i.CloudProviderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
