// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cloud_service_provider_focus_record.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createCloudServiceProviderFocusRecord = `-- name: CreateCloudServiceProviderFocusRecord :exec
INSERT INTO cloud_service_provider_focus_record (
    id, charge_batch_id,
    billed_cost, billing_account_id, billing_account_type, billing_currency,
    billing_period_end, billing_period_start, charge_category, charge_frequency,
    charge_period_end, charge_period_start, contracted_cost, effective_cost,
    host_provider_name, invoice_issuer_name, list_cost, service_category,
    service_name, service_provider_name, service_subcategory,
    allocated_method_details, allocated_method_id, allocated_resource_id, allocated_resource_name, allocated_tags,
    availability_zone, region_id, region_name,
    billing_account_name,
    capacity_reservation_id, capacity_reservation_status,
    charge_class, charge_description,
    commitment_discount_category, commitment_discount_id, commitment_discount_name, commitment_discount_quantity, commitment_discount_status, commitment_discount_type, commitment_discount_unit,
    consumed_quantity, consumed_unit,
    contract_applied, contracted_unit_price,
    invoice_id,
    list_unit_price,
    pricing_category, pricing_currency, pricing_currency_contracted_unit_price, pricing_currency_effective_cost, pricing_currency_list_unit_price, pricing_quantity, pricing_unit,
    resource_id, resource_name, resource_type,
    sku_id, sku_meter, sku_price_details, sku_price_id,
    sub_account_id, sub_account_name, sub_account_type,
    tags
) VALUES (
    ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?, ?,
    ?,
    ?, ?,
    ?, ?,
    ?, ?, ?, ?, ?, ?, ?,
    ?, ?,
    ?, ?,
    ?,
    ?,
    ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?,
    ?
)
`

type CreateCloudServiceProviderFocusRecordParams struct {
	ID                                 string
	ChargeBatchID                      string
	BilledCost                         float64
	BillingAccountID                   string
	BillingAccountType                 string
	BillingCurrency                    string
	BillingPeriodEnd                   time.Time
	BillingPeriodStart                 time.Time
	ChargeCategory                     string
	ChargeFrequency                    string
	ChargePeriodEnd                    time.Time
	ChargePeriodStart                  time.Time
	ContractedCost                     float64
	EffectiveCost                      float64
	HostProviderName                   string
	InvoiceIssuerName                  string
	ListCost                           float64
	ServiceCategory                    string
	ServiceName                        string
	ServiceProviderName                string
	ServiceSubcategory                 string
	AllocatedMethodDetails             sql.NullString
	AllocatedMethodID                  sql.NullString
	AllocatedResourceID                sql.NullString
	AllocatedResourceName              sql.NullString
	AllocatedTags                      sql.NullString
	AvailabilityZone                   sql.NullString
	RegionID                           sql.NullString
	RegionName                         sql.NullString
	BillingAccountName                 sql.NullString
	CapacityReservationID              sql.NullString
	CapacityReservationStatus          sql.NullString
	ChargeClass                        sql.NullString
	ChargeDescription                  sql.NullString
	CommitmentDiscountCategory         sql.NullString
	CommitmentDiscountID               sql.NullString
	CommitmentDiscountName             sql.NullString
	CommitmentDiscountQuantity         sql.NullFloat64
	CommitmentDiscountStatus           sql.NullString
	CommitmentDiscountType             sql.NullString
	CommitmentDiscountUnit             sql.NullString
	ConsumedQuantity                   sql.NullFloat64
	ConsumedUnit                       sql.NullString
	ContractApplied                    sql.NullString
	ContractedUnitPrice                sql.NullFloat64
	InvoiceID                          sql.NullString
	ListUnitPrice                      sql.NullFloat64
	PricingCategory                    sql.NullString
	PricingCurrency                    sql.NullString
	PricingCurrencyContractedUnitPrice sql.NullFloat64
	PricingCurrencyEffectiveCost       sql.NullFloat64
	PricingCurrencyListUnitPrice       sql.NullFloat64
	PricingQuantity                    sql.NullFloat64
	PricingUnit                        sql.NullString
	ResourceID                         sql.NullString
	ResourceName                       sql.NullString
	ResourceType                       sql.NullString
	SkuID                              sql.NullString
	SkuMeter                           sql.NullString
	SkuPriceDetails                    sql.NullString
	SkuPriceID                         sql.NullString
	SubAccountID                       sql.NullString
	SubAccountName                     sql.NullString
	SubAccountType                     sql.NullString
	Tags                               sql.NullString
}

func (q *Queries) CreateCloudServiceProviderFocusRecord(ctx context.Context, arg CreateCloudServiceProviderFocusRecordParams) error {
	_, err := q.db.ExecContext(ctx, createCloudServiceProviderFocusRecord,
		arg.ID,
		arg.ChargeBatchID,
		arg.BilledCost,
		arg.BillingAccountID,
		arg.BillingAccountType,
		arg.BillingCurrency,
		arg.BillingPeriodEnd,
		arg.BillingPeriodStart,
		arg.ChargeCategory,
		arg.ChargeFrequency,
		arg.ChargePeriodEnd,
		arg.ChargePeriodStart,
		arg.ContractedCost,
		arg.EffectiveCost,
		arg.HostProviderName,
		arg.InvoiceIssuerName,
		arg.ListCost,
		arg.ServiceCategory,
		arg.ServiceName,
		arg.ServiceProviderName,
		arg.ServiceSubcategory,
		arg.AllocatedMethodDetails,
		arg.AllocatedMethodID,
		arg.AllocatedResourceID,
		arg.AllocatedResourceName,
		arg.AllocatedTags,
		arg.AvailabilityZone,
		arg.RegionID,
		arg.RegionName,
		arg.BillingAccountName,
		arg.CapacityReservationID,
		arg.CapacityReservationStatus,
		arg.ChargeClass,
		arg.ChargeDescription,
		arg.CommitmentDiscountCategory,
		arg.CommitmentDiscountID,
		arg.CommitmentDiscountName,
		arg.CommitmentDiscountQuantity,
		arg.CommitmentDiscountStatus,
		arg.CommitmentDiscountType,
		arg.CommitmentDiscountUnit,
		arg.ConsumedQuantity,
		arg.ConsumedUnit,
		arg.ContractApplied,
		arg.ContractedUnitPrice,
		arg.InvoiceID,
		arg.ListUnitPrice,
		arg.PricingCategory,
		arg.PricingCurrency,
		arg.PricingCurrencyContractedUnitPrice,
		arg.PricingCurrencyEffectiveCost,
		arg.PricingCurrencyListUnitPrice,
		arg.PricingQuantity,
		arg.PricingUnit,
		arg.ResourceID,
		arg.ResourceName,
		arg.ResourceType,
		arg.SkuID,
		arg.SkuMeter,
		arg.SkuPriceDetails,
		arg.SkuPriceID,
		arg.SubAccountID,
		arg.SubAccountName,
		arg.SubAccountType,
		arg.Tags,
	)
	return err
}

const listAggregatedResourceChargesByBillingAccount = `-- name: ListAggregatedResourceChargesByBillingAccount :many
SELECT
    fr.resource_id AS resource_id,
    fr.resource_name AS resource_name,
    fr.resource_type AS resource_type,
    fr.service_name AS service_name,
    fr.service_category AS service_category,
    fr.billing_currency AS billing_currency,
    cspb.cloud_service_provider_id AS cloud_service_provider_id,
    SUM(fr.billed_cost) AS total_billed_cost,
    COUNT(*) AS line_item_count
FROM cloud_service_provider_focus_record fr
JOIN cloud_service_provider_charge_batch cspb ON cspb.id = fr.charge_batch_id
WHERE fr.billing_account_id = ?
GROUP BY fr.resource_id, fr.resource_name, fr.resource_type, fr.service_name, fr.service_category, fr.billing_currency, cspb.cloud_service_provider_id
ORDER BY total_billed_cost DESC
`

type ListAggregatedResourceChargesByBillingAccountRow struct {
	ResourceID             sql.NullString
	ResourceName           sql.NullString
	ResourceType           sql.NullString
	ServiceName            string
	ServiceCategory        string
	BillingCurrency        string
	CloudServiceProviderID string
	TotalBilledCost        sql.NullFloat64
	LineItemCount          int64
}

// Aggregated billed cost per resource, sourced entirely from the FOCUS records fetched
// directly from the CSP (not from anything reported by the billing provider).
func (q *Queries) ListAggregatedResourceChargesByBillingAccount(ctx context.Context, billingAccountID string) ([]ListAggregatedResourceChargesByBillingAccountRow, error) {
	rows, err := q.db.QueryContext(ctx, listAggregatedResourceChargesByBillingAccount, billingAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAggregatedResourceChargesByBillingAccountRow
	for rows.Next() {
		var i ListAggregatedResourceChargesByBillingAccountRow
		if err := rows.Scan(
			&i.ResourceID,
			&i.ResourceName,
			&i.ResourceType,
			&i.ServiceName,
			&i.ServiceCategory,
			&i.BillingCurrency,
			&i.CloudServiceProviderID,
			&i.TotalBilledCost,
			&i.LineItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCloudServiceProviderFocusRecordsByChargeBatch = `-- name: ListCloudServiceProviderFocusRecordsByChargeBatch :many
SELECT id, charge_batch_id, billed_cost, billing_account_id, billing_account_type, billing_currency, billing_period_end, billing_period_start, charge_category, charge_frequency, charge_period_end, charge_period_start, contracted_cost, effective_cost, host_provider_name, invoice_issuer_name, list_cost, service_category, service_name, service_provider_name, service_subcategory, allocated_method_details, allocated_method_id, allocated_resource_id, allocated_resource_name, allocated_tags, availability_zone, region_id, region_name, billing_account_name, capacity_reservation_id, capacity_reservation_status, charge_class, charge_description, commitment_discount_category, commitment_discount_id, commitment_discount_name, commitment_discount_quantity, commitment_discount_status, commitment_discount_type, commitment_discount_unit, consumed_quantity, consumed_unit, contract_applied, contracted_unit_price, invoice_id, list_unit_price, pricing_category, pricing_currency, pricing_currency_contracted_unit_price, pricing_currency_effective_cost, pricing_currency_list_unit_price, pricing_quantity, pricing_unit, resource_id, resource_name, resource_type, sku_id, sku_meter, sku_price_details, sku_price_id, sub_account_id, sub_account_name, sub_account_type, tags FROM cloud_service_provider_focus_record
WHERE charge_batch_id = ?
`

func (q *Queries) ListCloudServiceProviderFocusRecordsByChargeBatch(ctx context.Context, chargeBatchID string) ([]CloudServiceProviderFocusRecord, error) {
	rows, err := q.db.QueryContext(ctx, listCloudServiceProviderFocusRecordsByChargeBatch, chargeBatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CloudServiceProviderFocusRecord
	for rows.Next() {
		var i CloudServiceProviderFocusRecord
		if err := rows.Scan(
			&i.ID,
			&i.ChargeBatchID,
			&i.BilledCost,
			&i.BillingAccountID,
			&i.BillingAccountType,
			&i.BillingCurrency,
			&i.BillingPeriodEnd,
			&i.BillingPeriodStart,
			&i.ChargeCategory,
			&i.ChargeFrequency,
			&i.ChargePeriodEnd,
			&i.ChargePeriodStart,
			&i.ContractedCost,
			&i.EffectiveCost,
			&i.HostProviderName,
			&i.InvoiceIssuerName,
			&i.ListCost,
			&i.ServiceCategory,
			&i.ServiceName,
			&i.ServiceProviderName,
			&i.ServiceSubcategory,
			&i.AllocatedMethodDetails,
			&i.AllocatedMethodID,
			&i.AllocatedResourceID,
			&i.AllocatedResourceName,
			&i.AllocatedTags,
			&i.AvailabilityZone,
			&i.RegionID,
			&i.RegionName,
			&i.BillingAccountName,
			&i.CapacityReservationID,
			&i.CapacityReservationStatus,
			&i.ChargeClass,
			&i.ChargeDescription,
			&i.CommitmentDiscountCategory,
			&i.CommitmentDiscountID,
			&i.CommitmentDiscountName,
			&i.CommitmentDiscountQuantity,
			&i.CommitmentDiscountStatus,
			&i.CommitmentDiscountType,
			&i.CommitmentDiscountUnit,
			&i.ConsumedQuantity,
			&i.ConsumedUnit,
			&i.ContractApplied,
			&i.ContractedUnitPrice,
			&i.InvoiceID,
			&i.ListUnitPrice,
			&i.PricingCategory,
			&i.PricingCurrency,
			&i.PricingCurrencyContractedUnitPrice,
			&i.PricingCurrencyEffectiveCost,
			&i.PricingCurrencyListUnitPrice,
			&i.PricingQuantity,
			&i.PricingUnit,
			&i.ResourceID,
			&i.ResourceName,
			&i.ResourceType,
			&i.SkuID,
			&i.SkuMeter,
			&i.SkuPriceDetails,
			&i.SkuPriceID,
			&i.SubAccountID,
			&i.SubAccountName,
			&i.SubAccountType,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
