// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoice.sql

package db

import (
	"context"
	"strings"
	"time"
)

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoice (id, billing_account_id, billing_period_id, amount, currency, status, issued_at, due_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, billing_account_id, billing_period_id, amount, currency, status, issued_at, due_at
`

type CreateInvoiceParams struct {
	ID               string
	BillingAccountID string
	BillingPeriodID  string
	Amount           float64
	Currency         string
	Status           string
	IssuedAt         time.Time
	DueAt            time.Time
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, createInvoice,
		arg.ID,
		arg.BillingAccountID,
		arg.BillingPeriodID,
		arg.Amount,
		arg.Currency,
		arg.Status,
		arg.IssuedAt,
		arg.DueAt,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.BillingAccountID,
		&i.BillingPeriodID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.IssuedAt,
		&i.DueAt,
	)
	return i, err
}

const createInvoiceProviderLineItem = `-- name: CreateInvoiceProviderLineItem :one
INSERT INTO invoice_provider_line_item (id, invoice_id, cloud_service_provider_id, amount, merkle_root, batch_count, merkle_valid)
VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id, invoice_id, cloud_service_provider_id, amount, merkle_root, batch_count, merkle_valid
`

type CreateInvoiceProviderLineItemParams struct {
	ID                     string
	InvoiceID              string
	CloudServiceProviderID string
	Amount                 float64
	MerkleRoot             string
	BatchCount             int64
	MerkleValid            bool
}

func (q *Queries) CreateInvoiceProviderLineItem(ctx context.Context, arg CreateInvoiceProviderLineItemParams) (InvoiceProviderLineItem, error) {
	row := q.db.QueryRowContext(ctx, createInvoiceProviderLineItem,
		arg.ID,
		arg.InvoiceID,
		arg.CloudServiceProviderID,
		arg.Amount,
		arg.MerkleRoot,
		arg.BatchCount,
		arg.MerkleValid,
	)
	var i InvoiceProviderLineItem
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.CloudServiceProviderID,
		&i.Amount,
		&i.MerkleRoot,
		&i.BatchCount,
		&i.MerkleValid,
	)
	return i, err
}

const getInvoice = `-- name: GetInvoice :one
SELECT id, billing_account_id, billing_period_id, amount, currency, status, issued_at, due_at FROM invoice WHERE id = ?
`

func (q *Queries) GetInvoice(ctx context.Context, id string) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, getInvoice, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.BillingAccountID,
		&i.BillingPeriodID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.IssuedAt,
		&i.DueAt,
	)
	return i, err
}

const listInvoiceProviderLineItemsByInvoiceIDs = `-- name: ListInvoiceProviderLineItemsByInvoiceIDs :many
SELECT id, invoice_id, cloud_service_provider_id, amount, merkle_root, batch_count, merkle_valid FROM invoice_provider_line_item WHERE invoice_id IN (/*SLICE:invoice_ids*/?)
`

func (q *Queries) ListInvoiceProviderLineItemsByInvoiceIDs(ctx context.Context, invoiceIds []string) ([]InvoiceProviderLineItem, error) {
	query := listInvoiceProviderLineItemsByInvoiceIDs
	var queryParams []interface{}
	if len(invoiceIds) > 0 {
		for _, v := range invoiceIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:invoice_ids*/?", strings.Repeat(",?", len(invoiceIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:invoice_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvoiceProviderLineItem
	for rows.Next() {
		var i InvoiceProviderLineItem
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.CloudServiceProviderID,
			&i.Amount,
			&i.MerkleRoot,
			&i.BatchCount,
			&i.MerkleValid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByBillingAccount = `-- name: ListInvoicesByBillingAccount :many
SELECT id, billing_account_id, billing_period_id, amount, currency, status, issued_at, due_at FROM invoice WHERE billing_account_id = ? ORDER BY issued_at DESC
`

func (q *Queries) ListInvoicesByBillingAccount(ctx context.Context, billingAccountID string) ([]Invoice, error) {
	rows, err := q.db.QueryContext(ctx, listInvoicesByBillingAccount, billingAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.BillingAccountID,
			&i.BillingPeriodID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.IssuedAt,
			&i.DueAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
