// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type BillingAccount struct {
	ID                    string
	BillingProviderID     string
	Alias                 string
	CreatedAt             time.Time
	OnboardingRedirectUrl sql.NullString
	OnboardingComplete    sql.NullTime
}

type BillingAccountCostBatch struct {
	ID                     string
	BillingAccountID       string
	BillingPeriodID        string
	CloudServiceProviderID string
	TotalItems             int64
	TotalCost              float64
	BilledCurrency         string
	MerkelRoot             string
	BatchSignature         string
	CreatedAt              time.Time
	ReceivedAt             time.Time
}

type BillingProvider struct {
	ID             string
	Name           string
	ApiEndpointUrl string
}

type BillingProviderSupportedCloudProvider struct {
	ID                string
	BillingProviderID string
	Name              string
	ApiEndpointUrl    string
}

type CloudServiceProviderAccount struct {
	ID               string
	BillingAccountID string
	CloudProviderID  string
}
