// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type BillingAccount struct {
	ID                    string
	BillingProviderID     string
	Alias                 string
	CreatedAt             time.Time
	OnboardingRedirectUrl sql.NullString
	OnboardingComplete    sql.NullTime
}

type BillingProvider struct {
	ID             string
	Name           string
	ApiEndpointUrl string
}

type BillingProviderSupportedCloudProvider struct {
	ID                string
	BillingProviderID string
	Name              string
	ApiEndpointUrl    string
}

type CloudServiceProviderAccount struct {
	ID               string
	BillingAccountID string
	CloudProviderID  string
}
