// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type BillingAccount struct {
	ID                    string
	BillingProviderID     string
	Alias                 string
	CreatedAt             time.Time
	OnboardingRedirectUrl sql.NullString
	OnboardingComplete    sql.NullTime
}

type BillingAccountChargeBatch struct {
	ID                     string
	BillingAccountID       string
	BillingPeriodID        string
	CloudServiceProviderID string
	TotalItems             int64
	TotalCost              float64
	BilledCurrency         string
	MerkleRoot             string
	BatchSignature         string
	CreatedAt              time.Time
	ReceivedAt             time.Time
}

type BillingProvider struct {
	ID             string
	Name           string
	ApiEndpointUrl string
}

type CloudServiceProvider struct {
	ID                     string
	BillingProviderID      string
	Name                   string
	ApiEndpointUrl         string
	CustomerApiEndpointUrl string
}

type CloudServiceProviderAccount struct {
	ID                     string
	BillingAccountID       string
	CloudServiceProviderID string
}

type CloudServiceProviderChargeBatch struct {
	ID                     string
	BillingAccountID       string
	CloudServiceProviderID string
	TotalItems             int64
	TotalCost              float64
	BilledCurrency         string
	MerkleRoot             string
	BatchSignature         string
	CreatedAt              time.Time
	ReceivedAt             time.Time
}

type CloudServiceProviderFocusRecord struct {
	ID                                 string
	ChargeBatchID                      string
	BilledCost                         float64
	BillingAccountID                   string
	BillingAccountType                 string
	BillingCurrency                    string
	BillingPeriodEnd                   time.Time
	BillingPeriodStart                 time.Time
	ChargeCategory                     string
	ChargeFrequency                    string
	ChargePeriodEnd                    time.Time
	ChargePeriodStart                  time.Time
	ContractedCost                     float64
	EffectiveCost                      float64
	HostProviderName                   string
	InvoiceIssuerName                  string
	ListCost                           float64
	ServiceCategory                    string
	ServiceName                        string
	ServiceProviderName                string
	ServiceSubcategory                 string
	AllocatedMethodDetails             sql.NullString
	AllocatedMethodID                  sql.NullString
	AllocatedResourceID                sql.NullString
	AllocatedResourceName              sql.NullString
	AllocatedTags                      sql.NullString
	AvailabilityZone                   sql.NullString
	RegionID                           sql.NullString
	RegionName                         sql.NullString
	BillingAccountName                 sql.NullString
	CapacityReservationID              sql.NullString
	CapacityReservationStatus          sql.NullString
	ChargeClass                        sql.NullString
	ChargeDescription                  sql.NullString
	CommitmentDiscountCategory         sql.NullString
	CommitmentDiscountID               sql.NullString
	CommitmentDiscountName             sql.NullString
	CommitmentDiscountQuantity         sql.NullFloat64
	CommitmentDiscountStatus           sql.NullString
	CommitmentDiscountType             sql.NullString
	CommitmentDiscountUnit             sql.NullString
	ConsumedQuantity                   sql.NullFloat64
	ConsumedUnit                       sql.NullString
	ContractApplied                    sql.NullString
	ContractedUnitPrice                sql.NullFloat64
	InvoiceID                          sql.NullString
	ListUnitPrice                      sql.NullFloat64
	PricingCategory                    sql.NullString
	PricingCurrency                    sql.NullString
	PricingCurrencyContractedUnitPrice sql.NullFloat64
	PricingCurrencyEffectiveCost       sql.NullFloat64
	PricingCurrencyListUnitPrice       sql.NullFloat64
	PricingQuantity                    sql.NullFloat64
	PricingUnit                        sql.NullString
	ResourceID                         sql.NullString
	ResourceName                       sql.NullString
	ResourceType                       sql.NullString
	SkuID                              sql.NullString
	SkuMeter                           sql.NullString
	SkuPriceDetails                    sql.NullString
	SkuPriceID                         sql.NullString
	SubAccountID                       sql.NullString
	SubAccountName                     sql.NullString
	SubAccountType                     sql.NullString
	Tags                               sql.NullString
}

type Invoice struct {
	ID               string
	BillingAccountID string
	BillingPeriodID  string
	Amount           float64
	Currency         string
	Status           string
	IssuedAt         time.Time
	DueAt            time.Time
}

type InvoiceProviderLineItem struct {
	ID                     string
	InvoiceID              string
	CloudServiceProviderID string
	Amount                 float64
	MerkleRoot             string
	BatchCount             int64
}
