// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Andrew Rutherfoord"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/billing/accounts": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "billing"
                ],
                "summary": "Get all billing accounts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.billingAccountResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/billing/accounts/register": {
            "post": {
                "description": "Registers a new billing account with a billing provider and returns a redirect URL for the customer onboarding flow.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "billing"
                ],
                "summary": "Register billing account with billing provider",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.RegisterAcccountRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.RegisterAccountResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/billing/accounts/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "billing"
                ],
                "summary": "Get a billing account by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.billingAccountDetailResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/billing/accounts/{id}/charge-batches": {
            "get": {
                "description": "Each charge batch is returned once, with the billing provider's report and the cloud service provider's own report of the same batch ID side by side (either may be missing), plus a status indicating whether they agree.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "billing"
                ],
                "summary": "List charge batches for a billing account, merging the billing provider's and cloud provider's reports",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Billing account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.ChargeBatchEntry"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/billing/accounts/{id}/cloud-provider-accounts": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "billing"
                ],
                "summary": "List cloud providers linked to a billing account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.CloudProviderLink"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/billing/accounts/{id}/cloud-provider-accounts/complete": {
            "post": {
                "description": "Called by the frontend after the CSP redirect. Stores the CSP account link in the billing account.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "billing"
                ],
                "summary": "Complete cloud provider account onboarding",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Billing account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.completeCloudProviderOnboardingRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.CloudProviderLink"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/billing/accounts/{id}/cloud-provider-accounts/register": {
            "post": {
                "description": "Registers a new cloud provider account with the billing provider and returns a redirect URL for the customer onboarding flow.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "billing"
                ],
                "summary": "Register a cloud provider account with a billing account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.RegisterLinkedCloudProviderRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.RegisterAccountResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/billing/accounts/{id}/resource-charges": {
            "get": {
                "description": "Aggregates billed cost per resource entirely from the FOCUS line items fetched directly from the CSP (not from anything reported by the billing provider), so each row also shows which cloud service provider it came from.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "billing"
                ],
                "summary": "List aggregated billed cost per resource",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Billing account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.ResourceChargeEntry"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.ChargeBatchEntry": {
            "type": "object",
            "properties": {
                "batch_id": {
                    "type": "string"
                },
                "billing_account_id": {
                    "type": "string"
                },
                "billing_provider_report": {
                    "$ref": "#/definitions/handlers.chargeBatchReportEntry"
                },
                "cloud_provider_report": {
                    "$ref": "#/definitions/handlers.chargeBatchReportEntry"
                },
                "cloud_service_provider_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "handlers.CloudProviderLink": {
            "type": "object",
            "properties": {
                "billing_account_id": {
                    "type": "string"
                },
                "billing_currency": {
                    "type": "string"
                },
                "cloud_provider_account_id": {
                    "type": "string"
                },
                "cloud_provider_id": {
                    "type": "string"
                },
                "cloud_provider_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "total_cost": {
                    "type": "number"
                }
            }
        },
        "handlers.RegisterAcccountRequest": {
            "type": "object",
            "required": [
                "account_alias",
                "billing_provider_base_url",
                "return_url"
            ],
            "properties": {
                "account_alias": {
                    "type": "string"
                },
                "billing_provider_base_url": {
                    "type": "string"
                },
                "return_url": {
                    "description": "TODO: I'm not sure I like the frontend setting the URL... Might need to change this...",
                    "type": "string"
                }
            }
        },
        "handlers.RegisterAccountResponse": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "redirect_url": {
                    "type": "string"
                }
            }
        },
        "handlers.RegisterLinkedCloudProviderRequest": {
            "type": "object",
            "required": [
                "account_id",
                "cloud_provider_id",
                "return_url"
            ],
            "properties": {
                "account_id": {
                    "description": "The billing account ID to link the cloud provider to",
                    "type": "string"
                },
                "cloud_provider_id": {
                    "description": "The identifier from the billing provider metadata",
                    "type": "string"
                },
                "return_url": {
                    "type": "string"
                }
            }
        },
        "handlers.ResourceChargeEntry": {
            "type": "object",
            "properties": {
                "billing_currency": {
                    "type": "string"
                },
                "cloud_service_provider_id": {
                    "type": "string"
                },
                "line_item_count": {
                    "type": "integer"
                },
                "resource_id": {
                    "type": "string"
                },
                "resource_name": {
                    "type": "string"
                },
                "resource_type": {
                    "type": "string"
                },
                "service_category": {
                    "type": "string"
                },
                "service_name": {
                    "type": "string"
                },
                "total_billed_cost": {
                    "type": "number"
                }
            }
        },
        "handlers.billingAccountDetailResponse": {
            "type": "object",
            "properties": {
                "alias": {
                    "type": "string"
                },
                "billing_provider_id": {
                    "type": "string"
                },
                "billing_provider_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "supported_cloud_providers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.supportedCloudProviderEntry"
                    }
                }
            }
        },
        "handlers.billingAccountResponse": {
            "type": "object",
            "properties": {
                "alias": {
                    "type": "string"
                },
                "billing_provider_id": {
                    "type": "string"
                },
                "billing_provider_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "handlers.chargeBatchReportEntry": {
            "type": "object",
            "properties": {
                "batch_signature": {
                    "type": "string"
                },
                "billed_currency": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "merkle_root": {
                    "type": "string"
                },
                "received_at": {
                    "type": "string"
                },
                "total_cost": {
                    "type": "number"
                },
                "total_items": {
                    "type": "integer"
                }
            }
        },
        "handlers.completeCloudProviderOnboardingRequest": {
            "type": "object",
            "required": [
                "csp_provider_id"
            ],
            "properties": {
                "csp_provider_id": {
                    "type": "string"
                }
            }
        },
        "handlers.supportedCloudProviderEntry": {
            "type": "object",
            "properties": {
                "customer_api_endpoint_url": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Bearer \u003caccount_id\u003e",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8082",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "CSP Mock API",
	Description:      "Mock Cloud Service Provider billing API implementing the FOCUS spec.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
