// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Andrew Rutherfoord"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/.well-known/cloud-service-provider": {
            "get": {
                "description": "Returns metadata about the cloud service provider, such as provider ID and name. This is used by the billing provider or the customer metering service to identify and display information about the CSP.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "well-known"
                ],
                "summary": "Cloud Service Provider metadata",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cloudserviceprovider.Metadata"
                        }
                    }
                }
            }
        },
        "/billing-accounts": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "billing-accounts"
                ],
                "summary": "List all billing accounts for the authenticated customer",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_andrewrutherfoord_fed-bill-poc_csp-mock_internal_db.BillingAccount"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "billing-accounts"
                ],
                "summary": "Create a new billing account for the authenticated customer",
                "parameters": [
                    {
                        "description": "Billing account details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.createBillingAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_andrewrutherfoord_fed-bill-poc_csp-mock_internal_db.BillingAccount"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/billing-accounts/{account_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "billing-accounts"
                ],
                "summary": "Get a billing account by account ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Billing account ID",
                        "name": "account_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_andrewrutherfoord_fed-bill-poc_csp-mock_internal_db.BillingAccount"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/billing/accounts": {
            "post": {
                "description": "Called by the customer-billing service. Creates a pending onboarding session and returns a redirect URL for the customer to complete setup.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "billing-accounts"
                ],
                "summary": "Initiate a CSP billing account onboarding session",
                "parameters": [
                    {
                        "description": "Registration request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cloudserviceprovider.RegisterLinkedCloudProviderRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/cloudserviceprovider.RegisterLinkedCloudProviderResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/billing/accounts/records": {
            "post": {
                "description": "Called directly by the customer-billing service to independently verify what this CSP reported, without going through the billing provider.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "billing"
                ],
                "summary": "Get charge batches (including raw FOCUS line items) for a billing account",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cloudserviceprovider.GetBillingAccountRecordsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cloudserviceprovider.GetBillingAccountRecordsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/customer": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customer"
                ],
                "summary": "Get the authenticated customer",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_andrewrutherfoord_fed-bill-poc_csp-mock_internal_db.Customer"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/customer/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customer"
                ],
                "summary": "Register a new customer",
                "parameters": [
                    {
                        "description": "Customer details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.registerCustomerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_andrewrutherfoord_fed-bill-poc_csp-mock_internal_db.Customer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/onboarding/{session_id}": {
            "get": {
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "onboarding"
                ],
                "summary": "Render the CSP account onboarding form",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Onboarding session ID",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "tags": [
                    "onboarding"
                ],
                "summary": "Submit the CSP account onboarding form",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Onboarding session ID",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "303": {
                        "description": "See Other"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/resource-types": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "List all resource types offered by this CSP",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_andrewrutherfoord_fed-bill-poc_csp-mock_internal_config.ResourceType"
                            }
                        }
                    }
                }
            }
        },
        "/resource-types/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "Get a resource type by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Resource type ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_andrewrutherfoord_fed-bill-poc_csp-mock_internal_config.ResourceType"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/resources": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resources"
                ],
                "summary": "List all resources for the authenticated customer",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit the number of results returned",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_andrewrutherfoord_fed-bill-poc_csp-mock_internal_db.Resource"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resources"
                ],
                "summary": "Provision a new resource for the authenticated customer",
                "parameters": [
                    {
                        "description": "Resource details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.createResourceRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_andrewrutherfoord_fed-bill-poc_csp-mock_internal_db.Resource"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/resources/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resources"
                ],
                "summary": "Delete a resource by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Resource ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/resources/{id}/storage": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resources"
                ],
                "summary": "Update the storage GB for a resource",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Resource ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Storage details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.setStorageRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "cloudserviceprovider.GetBillingAccountRecordsRequest": {
            "type": "object",
            "properties": {
                "billing_account_id": {
                    "type": "string"
                },
                "from": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "cloudserviceprovider.GetBillingAccountRecordsResponse": {
            "type": "object",
            "properties": {
                "batches": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ChargeBatchDetail"
                    }
                },
                "count": {
                    "type": "integer"
                },
                "from": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "cloudserviceprovider.Metadata": {
            "type": "object",
            "properties": {
                "api_endpoint_url": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "supported_billing_providers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/cloudserviceprovider.SupportedCloudProviderMetadata"
                    }
                }
            }
        },
        "cloudserviceprovider.RegisterLinkedCloudProviderRequest": {
            "type": "object",
            "required": [
                "billing_account_id",
                "billing_provider_id",
                "return_url"
            ],
            "properties": {
                "billing_account_id": {
                    "type": "string"
                },
                "billing_provider_id": {
                    "type": "string"
                },
                "return_url": {
                    "type": "string"
                }
            }
        },
        "cloudserviceprovider.RegisterLinkedCloudProviderResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "redirect_url": {
                    "type": "string"
                }
            }
        },
        "cloudserviceprovider.SupportedCloudProviderMetadata": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_andrewrutherfoord_fed-bill-poc_csp-mock_internal_config.PricingConfig": {
            "type": "object",
            "properties": {
                "model": {
                    "type": "string"
                },
                "tiers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_andrewrutherfoord_fed-bill-poc_csp-mock_internal_config.PricingTier"
                    }
                },
                "unitPrice": {
                    "type": "number"
                }
            }
        },
        "github_com_andrewrutherfoord_fed-bill-poc_csp-mock_internal_config.PricingTier": {
            "type": "object",
            "properties": {
                "unitPrice": {
                    "type": "number"
                },
                "upToGB": {
                    "type": "integer"
                }
            }
        },
        "github_com_andrewrutherfoord_fed-bill-poc_csp-mock_internal_config.ResourceType": {
            "type": "object",
            "properties": {
                "billingUnit": {
                    "type": "string"
                },
                "configSchema": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "description": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "pricing": {
                    "$ref": "#/definitions/github_com_andrewrutherfoord_fed-bill-poc_csp-mock_internal_config.PricingConfig"
                },
                "serviceCategory": {
                    "$ref": "#/definitions/models.ServiceCategory"
                },
                "serviceName": {
                    "type": "string"
                },
                "serviceSubcategory": {
                    "$ref": "#/definitions/models.ServiceSubcategory"
                },
                "skuID": {
                    "type": "string"
                },
                "tags": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_andrewrutherfoord_fed-bill-poc_csp-mock_internal_db.BillingAccount": {
            "type": "object",
            "properties": {
                "accountID": {
                    "type": "string"
                },
                "billingProviderID": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "customerID": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_andrewrutherfoord_fed-bill-poc_csp-mock_internal_db.Customer": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_andrewrutherfoord_fed-bill-poc_csp-mock_internal_db.Resource": {
            "type": "object",
            "properties": {
                "billingAccountID": {
                    "type": "string"
                },
                "customerID": {
                    "type": "string"
                },
                "deletedAt": {
                    "description": "Soft delete timestamp",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "resourceType": {
                    "type": "string"
                },
                "startedAt": {
                    "type": "string"
                },
                "storageGB": {
                    "type": "number"
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "internal_handlers.createBillingAccountRequest": {
            "type": "object",
            "required": [
                "account_id",
                "billing_provider"
            ],
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "billing_provider": {
                    "type": "string"
                }
            }
        },
        "internal_handlers.createResourceRequest": {
            "type": "object",
            "required": [
                "billing_account_id",
                "resource_type"
            ],
            "properties": {
                "billing_account_id": {
                    "type": "string"
                },
                "resource_type": {
                    "type": "string"
                }
            }
        },
        "internal_handlers.registerCustomerRequest": {
            "type": "object",
            "required": [
                "email",
                "name"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_handlers.setStorageRequest": {
            "type": "object",
            "required": [
                "storage_gb"
            ],
            "properties": {
                "storage_gb": {
                    "type": "number"
                }
            }
        },
        "models.CapacityReservationStatus": {
            "type": "string",
            "enum": [
                "used",
                "unused"
            ],
            "x-enum-varnames": [
                "CapacityReservationStatusUsed",
                "CapacityReservationStatusUnused"
            ]
        },
        "models.ChargeBatchDetail": {
            "type": "object",
            "properties": {
                "batch_id": {
                    "type": "string"
                },
                "batch_signature": {
                    "type": "string"
                },
                "billed_currency": {
                    "type": "string"
                },
                "billing_account_id": {
                    "type": "string"
                },
                "billing_provider_id": {
                    "type": "string"
                },
                "cloud_service_provider_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "line_item_count": {
                    "type": "integer"
                },
                "line_items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.FocusLineItem"
                    }
                },
                "merkle_root": {
                    "type": "string"
                },
                "total_billed_cost": {
                    "type": "number"
                }
            }
        },
        "models.CommitmentDiscountCategory": {
            "type": "string",
            "enum": [
                "spend",
                "usage"
            ],
            "x-enum-varnames": [
                "CommitmentDiscountCategorySpend",
                "CommitmentDiscountCategoryUsage"
            ]
        },
        "models.CommitmentDiscountStatus": {
            "type": "string",
            "enum": [
                "used",
                "unused"
            ],
            "x-enum-varnames": [
                "CommitmentDiscountStatusUsed",
                "CommitmentDiscountStatusUnused"
            ]
        },
        "models.FocusLineItem": {
            "type": "object",
            "properties": {
                "allocated_method_details": {
                    "description": "Optional Fields - Allocation",
                    "type": "string"
                },
                "allocated_method_id": {
                    "type": "string"
                },
                "allocated_resource_id": {
                    "type": "string"
                },
                "allocated_resource_name": {
                    "type": "string"
                },
                "allocated_tags": {
                    "type": "string"
                },
                "availability_zone": {
                    "description": "Optional Fields - Location",
                    "type": "string"
                },
                "billed_cost": {
                    "description": "Required Fields",
                    "type": "number"
                },
                "billing_account_id": {
                    "type": "string"
                },
                "billing_account_name": {
                    "description": "Optional Fields - Billing Account",
                    "type": "string"
                },
                "billing_account_type": {
                    "type": "string"
                },
                "billing_currency": {
                    "type": "string"
                },
                "billing_period_end": {
                    "type": "string"
                },
                "billing_period_start": {
                    "type": "string"
                },
                "capacity_reservation_id": {
                    "description": "Optional Fields - Capacity Reservation",
                    "type": "string"
                },
                "capacity_reservation_status": {
                    "$ref": "#/definitions/models.CapacityReservationStatus"
                },
                "charge_category": {
                    "type": "string"
                },
                "charge_class": {
                    "description": "Optional Fields - Charge Details",
                    "type": "string"
                },
                "charge_description": {
                    "type": "string"
                },
                "charge_frequency": {
                    "type": "string"
                },
                "charge_period_end": {
                    "type": "string"
                },
                "charge_period_start": {
                    "type": "string"
                },
                "commitment_discount_category": {
                    "description": "Optional Fields - Commitment Discount",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.CommitmentDiscountCategory"
                        }
                    ]
                },
                "commitment_discount_id": {
                    "type": "string"
                },
                "commitment_discount_name": {
                    "type": "string"
                },
                "commitment_discount_quantity": {
                    "type": "number"
                },
                "commitment_discount_status": {
                    "$ref": "#/definitions/models.CommitmentDiscountStatus"
                },
                "commitment_discount_type": {
                    "type": "string"
                },
                "commitment_discount_unit": {
                    "type": "string"
                },
                "consumed_quantity": {
                    "description": "Optional Fields - Consumption",
                    "type": "number"
                },
                "consumed_unit": {
                    "type": "string"
                },
                "contract_applied": {
                    "description": "Optional Fields - Contract",
                    "type": "string"
                },
                "contracted_cost": {
                    "type": "number"
                },
                "contracted_unit_price": {
                    "type": "number"
                },
                "effective_cost": {
                    "type": "number"
                },
                "host_provider_name": {
                    "type": "string"
                },
                "invoice_id": {
                    "description": "Optional Fields - Invoice",
                    "type": "string"
                },
                "invoice_issuer_name": {
                    "type": "string"
                },
                "list_cost": {
                    "type": "number"
                },
                "list_unit_price": {
                    "description": "Optional Fields - Pricing",
                    "type": "number"
                },
                "pricing_category": {
                    "type": "string"
                },
                "pricing_currency": {
                    "type": "string"
                },
                "pricing_currency_contracted_unit_price": {
                    "type": "number"
                },
                "pricing_currency_effective_cost": {
                    "type": "number"
                },
                "pricing_currency_list_unit_price": {
                    "type": "number"
                },
                "pricing_quantity": {
                    "type": "number"
                },
                "pricing_unit": {
                    "type": "string"
                },
                "region_id": {
                    "type": "string"
                },
                "region_name": {
                    "type": "string"
                },
                "resource_id": {
                    "description": "Optional Fields - Resource",
                    "type": "string"
                },
                "resource_name": {
                    "type": "string"
                },
                "resource_type": {
                    "type": "string"
                },
                "service_category": {
                    "$ref": "#/definitions/models.ServiceCategory"
                },
                "service_name": {
                    "type": "string"
                },
                "service_provider_name": {
                    "type": "string"
                },
                "service_subcategory": {
                    "$ref": "#/definitions/models.ServiceSubcategory"
                },
                "sku_id": {
                    "description": "Optional Fields - SKU",
                    "type": "string"
                },
                "sku_meter": {
                    "type": "string"
                },
                "sku_price_details": {
                    "type": "string"
                },
                "sku_price_id": {
                    "type": "string"
                },
                "sub_account_id": {
                    "description": "Optional Fields - Sub Account",
                    "type": "string"
                },
                "sub_account_name": {
                    "type": "string"
                },
                "sub_account_type": {
                    "type": "string"
                },
                "tags": {
                    "description": "Optional Fields - Tags",
                    "type": "string"
                }
            }
        },
        "models.ServiceCategory": {
            "type": "string",
            "enum": [
                "ai_and_machine_learning",
                "analytics",
                "business_applications",
                "compute",
                "databases",
                "developer_tools",
                "multicloud",
                "identity",
                "integration",
                "internet_of_things",
                "management_and_governance",
                "media",
                "migration",
                "mobile",
                "networking",
                "security",
                "storage",
                "web",
                "other"
            ],
            "x-enum-varnames": [
                "ServiceCategoryAIAndMachineLearning",
                "ServiceCategoryAnalytics",
                "ServiceCategoryBusinessApplications",
                "ServiceCategoryCompute",
                "ServiceCategoryDatabases",
                "ServiceCategoryDeveloperTools",
                "ServiceCategoryMulticloud",
                "ServiceCategoryIdentity",
                "ServiceCategoryIntegration",
                "ServiceCategoryInternetOfThings",
                "ServiceCategoryManagementGovernance",
                "ServiceCategoryMedia",
                "ServiceCategoryMigration",
                "ServiceCategoryMobile",
                "ServiceCategoryNetworking",
                "ServiceCategorySecurity",
                "ServiceCategoryStorage",
                "ServiceCategoryWeb",
                "ServiceCategoryOther"
            ]
        },
        "models.ServiceSubcategory": {
            "type": "string",
            "enum": [
                "ai_platforms",
                "bots",
                "generative_ai",
                "machine_learning",
                "natural_language_processing",
                "other_ai_and_machine_learning",
                "analytics_platforms",
                "business_intelligence",
                "data_processing",
                "search",
                "streaming_analytics",
                "other_analytics",
                "productivity_and_collaboration",
                "other_business_applications",
                "containers",
                "end_user_computing",
                "quantum_compute",
                "serverless_compute",
                "virtual_machines",
                "other_compute",
                "caching",
                "data_warehouses",
                "ledger_databases",
                "nosql_databases",
                "relational_databases",
                "time_series_databases",
                "other_databases",
                "developer_platforms",
                "continuous_integration_and_deployment",
                "development_environments",
                "source_code_management",
                "quality_assurance",
                "other_developer_tools",
                "identity_and_access_management",
                "other_identity",
                "api_management",
                "messaging",
                "workflow_orchestration",
                "other_integration",
                "iot_analytics",
                "iot_platforms",
                "other_internet_of_things",
                "architecture",
                "compliance",
                "cost_management",
                "data_governance",
                "disaster_recovery",
                "endpoint_management",
                "observability",
                "support",
                "other_management_and_governance",
                "content_creation",
                "gaming",
                "media_streaming",
                "mixed_reality",
                "other_media",
                "data_migration",
                "resource_migration",
                "other_migration",
                "other_mobile",
                "multicloud_integration",
                "other_multicloud",
                "application_networking",
                "content_delivery",
                "network_connectivity",
                "network_infrastructure",
                "network_routing",
                "network_security",
                "other_networking",
                "secret_management",
                "security_posture_management",
                "threat_detection_and_response",
                "other_security",
                "backup_storage",
                "block_storage",
                "file_storage",
                "object_storage",
                "storage_platforms",
                "other_storage",
                "application_platforms",
                "other_web",
                "other_other"
            ],
            "x-enum-varnames": [
                "ServiceSubcategoryAIPlatforms",
                "ServiceSubcategoryBots",
                "ServiceSubcategoryGenerativeAI",
                "ServiceSubcategoryMachineLearning",
                "ServiceSubcategoryNaturalLanguageProcessing",
                "ServiceSubcategoryOtherAIAndML",
                "ServiceSubcategoryAnalyticsPlatforms",
                "ServiceSubcategoryBusinessIntelligence",
                "ServiceSubcategoryDataProcessing",
                "ServiceSubcategorySearch",
                "ServiceSubcategoryStreamingAnalytics",
                "ServiceSubcategoryOtherAnalytics",
                "ServiceSubcategoryProductivityCollaboration",
                "ServiceSubcategoryOtherBusinessApplications",
                "ServiceSubcategoryContainers",
                "ServiceSubcategoryEndUserComputing",
                "ServiceSubcategoryQuantumCompute",
                "ServiceSubcategoryServerlessCompute",
                "ServiceSubcategoryVirtualMachines",
                "ServiceSubcategoryOtherCompute",
                "ServiceSubcategoryCaching",
                "ServiceSubcategoryDataWarehouses",
                "ServiceSubcategoryLedgerDatabases",
                "ServiceSubcategoryNoSQLDatabases",
                "ServiceSubcategoryRelationalDatabases",
                "ServiceSubcategoryTimeSeriesDatabases",
                "ServiceSubcategoryOtherDatabases",
                "ServiceSubcategoryDeveloperPlatforms",
                "ServiceSubcategoryCICD",
                "ServiceSubcategoryDevelopmentEnvironments",
                "ServiceSubcategorySourceCodeManagement",
                "ServiceSubcategoryQualityAssurance",
                "ServiceSubcategoryOtherDeveloperTools",
                "ServiceSubcategoryIAM",
                "ServiceSubcategoryOtherIdentity",
                "ServiceSubcategoryAPIManagement",
                "ServiceSubcategoryMessaging",
                "ServiceSubcategoryWorkflowOrchestration",
                "ServiceSubcategoryOtherIntegration",
                "ServiceSubcategoryIoTAnalytics",
                "ServiceSubcategoryIoTPlatforms",
                "ServiceSubcategoryOtherIoT",
                "ServiceSubcategoryArchitecture",
                "ServiceSubcategoryCompliance",
                "ServiceSubcategoryCostManagement",
                "ServiceSubcategoryDataGovernance",
                "ServiceSubcategoryDisasterRecovery",
                "ServiceSubcategoryEndpointManagement",
                "ServiceSubcategoryObservability",
                "ServiceSubcategorySupport",
                "ServiceSubcategoryOtherMgmtGovernance",
                "ServiceSubcategoryContentCreation",
                "ServiceSubcategoryGaming",
                "ServiceSubcategoryMediaStreaming",
                "ServiceSubcategoryMixedReality",
                "ServiceSubcategoryOtherMedia",
                "ServiceSubcategoryDataMigration",
                "ServiceSubcategoryResourceMigration",
                "ServiceSubcategoryOtherMigration",
                "ServiceSubcategoryOtherMobile",
                "ServiceSubcategoryMulticloudIntegration",
                "ServiceSubcategoryOtherMulticloud",
                "ServiceSubcategoryApplicationNetworking",
                "ServiceSubcategoryContentDelivery",
                "ServiceSubcategoryNetworkConnectivity",
                "ServiceSubcategoryNetworkInfrastructure",
                "ServiceSubcategoryNetworkRouting",
                "ServiceSubcategoryNetworkSecurity",
                "ServiceSubcategoryOtherNetworking",
                "ServiceSubcategorySecretManagement",
                "ServiceSubcategorySecurityPostureMgmt",
                "ServiceSubcategoryThreatDetectionResponse",
                "ServiceSubcategoryOtherSecurity",
                "ServiceSubcategoryBackupStorage",
                "ServiceSubcategoryBlockStorage",
                "ServiceSubcategoryFileStorage",
                "ServiceSubcategoryObjectStorage",
                "ServiceSubcategoryStoragePlatforms",
                "ServiceSubcategoryOtherStorage",
                "ServiceSubcategoryApplicationPlatforms",
                "ServiceSubcategoryOtherWeb",
                "ServiceSubcategoryOtherOther"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Bearer \u003caccount_id\u003e",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "CSP Mock Customer API",
	Description:      "Mock Cloud Service Provider customer billing API implementing the FOCUS spec.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
